# Generated by Django 3.2.3 on 2021-05-25 02:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('profile_photo', models.ImageField(upload_to='profile_images')),
                ('flipped_profile_photo', models.ImageField(upload_to='flipped_profile_images')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.CharField(choices=[('Pending', 'pending'), ('Rejected', 'rejected'), ('Matched', 'matched')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to='profiles.profile')),
                ('requested_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_profile', to='profiles.profile')),
            ],
            options={
                'db_table': 'profile_matches',
            },
        ),
    ]
