# Generated by Django 3.2.3 on 2021-05-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210525_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilematch',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profilematch',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='profiles.profile'),
        ),
    ]
